name: $(Build.SourceBranch)-$(date:yyyyMMdd):$(rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'eu.gcr.io/prod-ip/ssb/ssbno/archive-renderer'
  - name: repoName
    value: 'prod-bip/ssb/ssbno/archive-renderer'
  - name: tag
    value: $(Build.SourceBranchName)-archive-renderer-$(fullSha)

jobs:
  - job: buildTestDockerBuildDockerPush
    displayName: 'Test/Build app and docker image'
    steps:
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          repository: $(imageName)
          command: 'build'
          dockerfile: '$(Build.SourceDirectory)/Dockerfile'
          tags: |
            $(tag)

      - task: Docker@2
        displayName: 'Login to GCR'
        inputs:
          command: login
          containerRegistry: gcrServiceConnection

      - task: Docker@2
        displayName: 'Push image'
        inputs:
          ContainerRegistry: |
            gcrServiceConnection
          repository: $(repoName)
          command: 'push'
          tags: |
            $(tag)


