version: '3'

services:
  owb:
    build:
      context: ../openwayback
      dockerfile: Dockerfile
    volumes:
      - ../openwayback/ssb-archive:/mnt/storage/warcs/
    ports:
      - 8080:8080

  openresty:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - SITE_URL=https://www.qa.ssb.no

    ports:
      - 6060:6060

