FROM openresty/openresty:alpine-fat

ENV PATH="/usr/local/openresty/luajit/bin:${PATH}"
RUN luarocks install gumbo
RUN luarocks install lua-resty-http
RUN luarocks install luasocket
RUN luarocks install luasec OPENSSL_DIR=/usr/local/openresty/openssl

# copy main config
COPY ./openresty/nginx.dev.conf /usr/local/openresty/nginx/conf/nginx.conf

# copy certificates
COPY ./openresty/secure/ /secure/

# copy lua modules
COPY ./lua-modules/ /usr/local/openresty/lualib/

RUN ls -l /secure



