version: '3'

services:
  owb:
    build:
      context: ../openwayback
      dockerfile: Dockerfile
    volumes:
      - ../openwayback/ssb-archive:/mnt/storage/warcs/
    environment:
      - WAYBACK_URL_PREFIX=http://owb:8080
    ports:
      - 8080:8080

  openresty:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - OWB_URL=http://owb:8080
      - SITE_URL=https://www.qa.ssb.no
      - RENDERER_URL=http://localhost:6060/
    ports:
      - 6060:6060

