FROM openresty/openresty:alpine-fat

RUN /usr/local/openresty/luajit/bin/luarocks install gumbo
RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http

# copy main config
COPY ./openresty/nginx.dev.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY ./openresty/handler.lua /usr/local/openresty/nginx/handler.lua

# copy lua modules
COPY ./lua-modules/composer.lua /usr/local/openresty/lualib/composer.lua



